### ISSUE TITLE
Getting apt conf file prompt using package install mode

### ISSUE THREAD

**Issue by adampats** [chef-cookbooks/docker#595]
My wrapper cookbook leverages the `docker_service` resource and `install_method 'package'` to install docker-engine, but I am getting prompted by apt when I have a non-standard/default `/etc/init/docker.conf ` file present (which is necessary in my environment).  I thought that using Chef's `package` command set `DEBIAN_FRONTEND='noninteractive'` by default?  Somehow this recipe is "bypassing" that...

My recipe (called infradev-docker):
```ruby
docker_service 'default' do
  version '1.9.1'
  dns '10.0.0.2'
  group 'docker'
  graph '/opt/docker'
  install_method 'package'
  action [:create, :start]
end
```

Resulting chef-client run errors:

> STDERR: Configuration file '/etc/init/docker.conf'
==> File on system created by you or by a script.
      ==> File also in package provided by package maintainer.
        What would you like to do about it ?  Your options are:
         Y or I  : install the package maintainer's version
         N or O  : keep your currently-installed version
           D     : show the differences between the versions
           Z     : start a shell to examine the situation
      The default action is to keep your current version.
     *** docker.conf (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package docker-engine (--configure):
      EOF on stdin at conffile prompt
     Errors were encountered while processing:
      docker-engine
     E: Sub-process /usr/bin/dpkg returned an error code (1)
     ---- End output of apt-get -q -y install docker-engine=1.9.1-0~trusty ----
     Ran apt-get -q -y install docker-engine=1.9.1-0~trusty returned 100

> [2015-12-21T13:17:20-08:00] ERROR: docker_service[default] (infradev-docker::docker line 41) had an error: Mixlib::ShellOut::ShellCommandFailed: docker_installation_package[default] (/var/chef/cache/cookbooks/docker/libraries/docker_service.rb line 52) had an error: Mixlib::ShellOut::ShellCommandFailed: apt_package[docker-engine] (/var/chef/cache/cookbooks/docker/libraries/docker_installation_package.rb line 16) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'

This doesn't make sense to me, because I can see that the recipe is just using `package` here:
https://github.com/chef-cookbooks/docker/blob/master/libraries/docker_installation_package.rb#L16

For testing, I added an ENV declaration right before I call this resource, which makes it work after a 2nd converge on the node, which also doesn't make sense to me:

```ruby
ENV['DEBIAN_FRONTEND'] = 'noninteractive'
```

**Comment by chasebolt** [comment]
This seems to be the issue here. https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/92265

`noninteractive` flag doesnt appear to work when it comes down to overwriting a config file.

this brings up an interesting point for upgrades, since we are managing the file this will trigger when you bump from docker version 1.8.3 to 19.1 and so on.

**Comment by briceo** [comment]
Rather than trying to take ownership of the service script (upstart or systemd) when using the package installation method, write all of the `DOCKER_OPTS` to `/etc/default/docker`.  It appears that the delivered startup scripts that are deployed with the docker-engine package attempts to load the `/etc/default/docker` file.

Then the cookbook could be changed to only create the startup scripts (for their respective startup types) *if* the startup script wasn't already there (and have it also use the `/etc/default/docker` file for the options).  Then the docker-engine package version of the startup scripts will continue to be used and this cookbook can still manage the configuration it needs just through a slightly different way.

**Comment by jperville** [comment]
Agree with @briceo . As far as I remember, older version of this cookbook (circa version 2.0) would serialize the docker_service options into `/etc/default/docker` (shell script sourced by every docker init script), which was quite fine. With current version, the init script is modified each time the docker_service options change, and the /etc/default/docker file is left with its default content, all commented out, which is a regression IMO.

**Comment by gionn** [comment]
Hit on this as well, the solutions should be installing the package as suggested here: https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/92265/comments/8

**Comment by someara** [comment]
I revamped the upstart bits in 2.4.17. This should is fixed up now and utilizes the upstart config from the package and /etc/defaults.
