### ISSUE TITLE
Default Docker CMD not updated on image update

### ISSUE THREAD

**Issue by colinbankier** [chef-cookbooks/docker#673]
I'm using this cookbook to run a container that specifies a default CMD in the dockerfile.
For example, my Dockerfile has the line

```
CMD /usr/src/run.sh
```

If I run the container like:

```ruby
docker_image "my_image" do
  tag 'latest'
  action :pull
  notifies :redeploy, 'docker_container[my_container]', :delayed
end

docker_container "my_container" do
  repo "my_image"
  tag 'latest'
  port "8080:8080"
  restart_policy 'always'
end
```

This runs fine.
If I push a version of the image that changes the default CMD, e.g. update the Dockerfile with

```
CMD /usr/src/run_new.sh
```

and re-run the recipe, the new image is pulled, and run, BUT with the old command.
When I run `docker ps` I see '/usr/src/run.sh' as the command, but expect '/usr/src/run_new.sh'. Yet the image is the new one, containing other updates if things other than the CMD are updated.

**Comment by chasebolt** [comment]
this is an issue from https://github.com/chef-cookbooks/docker/issues/619

**Comment by clearmeasurebrian** [comment]
We're seeing this issue as well. Any updates or workarounds for this?

**Comment by someara** [comment]
I can't seem to replicate this one...

https://github.com/chef-cookbooks/docker/commit/8014525467dcb1075f44d9f45b849283144c26f0

The general strategy for testing this kinda thing is:
- Edit a recipe ran by a test-kitchen suite
- Set up the preconditions with executes and markers
- Replicate (un)expected behavior in recipe
- Test for evidence with inspec

I did my best to set up the conditions you described with the above commit... but can't seem to get it to fail.

I even tried commenting out the bottom three resources, converging, putting them back, and converging again across multiple chef-client runs.

Am I misunderstanding the issue here?

-s

**Comment by chasebolt** [comment]
so this was an issue i struggled with in the past and had tests that replicated it. went back and reran my tests and everything is working as it should now. i think this issue with load_current_value and properties has been resolved in newer version of chef/compat_resource.

https://github.com/chef-cookbooks/docker/pull/734 is a good explanation of what was going on.

i think it is safe to close this out.

**Comment by someara** [comment]
Closing for now. Thanks everyone!
-s
