### ISSUE TITLE
log_opts not working on docker_container

### ISSUE THREAD

**Issue by rajeshj-rpx** [chef-cookbooks/docker#705]
### Cookbook version
2.6.6

### Chef-client version
12.4.1
### Platform Details
Amazon Linux 
### Scenario:
I am trying to use log_opts for docker_container for use in my CLS. Docker container hangs after and fails to converge after 20s
### Steps to Reproduce:
create a docker_container resource and provide log_opts as below
 log_opts "max-size=1m env=#{node.chef_environment}"
### Expected Result:
On next converge, docker json logs should have these values set in.
### Actual Result:
Docker::Error::TimeoutError: Container xxxxx failed to change to running state after 20 seconds

**Comment by rajeshj-rpx** [comment]
Please advise, it is kind of blocker to us

**Comment by vladzu** [comment]
docker/libraries/helpers_service.rb  line 180 
 -       log_opts.each { |log_opt| opts << "--log-opt=#{log_opt}" } if log_opts
 +       log_opts.each { |log_opt| opts << "--log-opt #{log_opt}" } if log_opts

**Comment by hdimitriou** [comment]
@vladzu I think he is referring to the docker_container part which is coded at docker/libraries/helpers_container.rb line 20

@rajeshj-rpx since I was also looking for it, in your code define a variable (Hash) like this:
log_options = {"max-size" => "1m", "max-file" => "2", "labels" => "label1,label1", "env" => "dev_env"}

and then on the docker_container resouce do: 
log_opts log_options

From what I saw on the code (at least from what I understand..), if you define log_opts as a string on the docker_container it can only hold one attribute and not more..If that is intended I guess ticket could be resolved

**Comment by chasebolt** [comment]
log_opts can take a string if it is a single option. Or an array for multiple options. You are passing multiple options as a string which is not supported.
