### ISSUE TITLE
Docker Resources are Libraries Resources/Providers instead of Custom Resources 12.5-style

### ISSUE THREAD

**Issue by dmlb2000** [chef-cookbooks/docker#805]
I'm not sure what the going forward plan is and why docker isn't necessarily following the docs provided by chef. So I figured I'd ask.

According to [this link](https://docs.chef.io/custom_resources_notes.html#library-resources-providers) the docker cookbook isn't following the recommended way of writing resources in a cookbook. Is there a plan to move toward the more recommended way of creating custom resources? or are there technical hurdles that need to be overcome to move to that pattern of creating resources?

**Comment by someara** [comment]
"Recommended" is relative. I recommend doing it this way. 

Using the resources/ directory will magically name your class for you based on the file name.

Magic is bad.

This is more explicit. It also gives you something to search for in you text editor.

Also, I hope to one day include docker_resource into core Chef.... doing it this way, you can just move the file instead of having to go back in and un-magical-ify it.

-s

**Comment by someara** [comment]
This patter is also used in mysql, httpd, etcd, and other cookbooks under chef-cookbooks.

**Comment by dmlb2000** [comment]
@someara 

So I guess the argument for whether to use one way or the other comes down to your proficiency with Ruby (and a bit of preference)? The libraries resources method is more explicit for folks who know a bit of Ruby and how it organizes things. If you aren't as familiar with Ruby you should use the resources 12.5-style of custom resources?

**Comment by someara** [comment]
Again, these *are* 12.5 style Custom Resources. They just don't use the
magic directory.

They were among the first ever written. This cookbook drove a lot of
features in the new DSL... it was developed in tandem leading up to 12.5.

The major indicator is the use of :property instead of :attribute
Because they're in libraries/ you can see that they subclass Chef::Resource
instead of Chef::Resource::LWRPBase.

Docker ends up needing a lot of helper libraries to keep the reader sane
and resource patterns visible.

Using the magic directory, someone would need to jump back and forth
between two directories while trying to follow code instead of just two
files.
You can't put the helpers in the magic directory because the magic would be
applied inappropriately.

For the record, I've never bought the whole "Some people aren't as familiar
with Ruby" argument as an excuse to indulge in magic. If anything it's an
argument against it. This code is being used for operations, and will very
often be read for the first time in an emergency.
Being explicit is better for those not familiar with Ruby.

-s
