### ISSUE TITLE
docker-api gem cannot be installed in airgapped environment

### ISSUE THREAD

**Issue by swimfrog** [chef-cookbooks/docker#860]
### Cookbook version
2.15.6

### Chef-client version
12.11.18

### Platform Details
Oracle Linux 7.3

### Scenario:
When running the cookbook when rubygems.org is not reachable (i.e. behind firewall with no proxy setting specified), the cookbook run fails.

### Steps to Reproduce:
1. Use iptables or something to block access to api.rubygems.org:443
1. Run the cookbook

### Expected Result:
Since the gems are vendored locally, I would expect the included gems to be installed from the cookbook.

### Actual Result:
Fails with an error like the following:

```
Installing Cookbook Gems:
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/docker/libraries/_autoload.rb
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
chef_gem[docker-api] (dynamically defined) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of /opt/chef/embedded/bin/gem install docker-api -q --no-rdoc --no-ri -v "= 1.33.2" ----
STDOUT:
STDERR: ERROR:  Could not find a valid gem 'docker-api' (= 1.33.2), here is why:
          Unable to download data from https://rubygems.org/ - Errno::EHOSTUNREACH: No route to host - connect(2) for "api.rubygems.org" port 443 (https://api.rubygems.org/specs.4.8.gz)
---- End output of /opt/chef/embedded/bin/gem install docker-api -q --no-rdoc --no-ri -v "= 1.33.2" ----
Ran /opt/chef/embedded/bin/gem install docker-api -q --no-rdoc --no-ri -v "= 1.33.2" returned 2

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/docker/libraries/_autoload.rb:11:in `rescue in <top (required)>'
  /var/chef/cache/cookbooks/docker/libraries/_autoload.rb:1:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/docker/libraries/_autoload.rb:

  4:    unless defined?(ChefSpec)
  5:      run_context = Chef::RunContext.new(Chef::Node.new, {}, Chef::EventDispatch::Dispatcher.new)
  6:
  7:      require 'chef/resource/chef_gem'
  8:
  9:      docker = Chef::Resource::ChefGem.new('docker-api', run_context)
 10:      docker.version '= 1.33.2'
 11>>     docker.run_action(:install)
 12:    end
 13:  end
 14:

Platform:
---------
x86_64-linux


Running handlers:
Running handlers complete
Chef Client failed. 0 resources updated in 26 seconds
```

**Comment by iennae** [comment]
As long as you are running Chef 13, it sounds like you need to configure the `rubygems_url` configuration in your client.rb so that gems install from the appropriate place.

**Comment by swimfrog** [comment]
My Chef version is 12.11.18. Setting rubygems_url doesn't have any effect.

From looking at the code, the intention with the current setup appears to be that the gems should be installed from `files/default/vendor` dir inside the cookbook, so that the cookbook can run without any external gem sources.

However, it seems unlikely that the current code really will install the gems from the local cookbook -- docker-api and its dependencies are probably just retrieved from rubygems, no matter that they are included in the cookbook.

**Comment by chasebolt** [comment]
vendoring of the docker gem was removed in v2.14.3

**Comment by swimfrog** [comment]
odd... I see what you mean that the vendored files were removed via #815 if you look at github, but if you download v2.15.6 of the cookbook from supermarket, the `files/default/vendor` dir and gemfiles, etc are still there in the downloaded archive:

https://supermarket.chef.io/cookbooks/docker/versions/2.15.6/download

**Comment by swimfrog** [comment]
So, since docker-api is not vendored by the cookbook, my understanding is that this cookbook can't be used if there is no locally-accessible gem source available. Is any other workaround possible?

**Comment by someara** [comment]
Hi. 

Just dropping a note here...

@lamont-granquist suggested the solution to this should be to use the loading technique from the AWS cookbook. 

I'd love to see this fixed, but haven't had a chance to fully understand the technique yet

-s

**Comment by lamont-granquist** [comment]
That isn't a solution to airgapping the gem distribution.

Originally we used vendoring gems to install them earlier than chef_gem could install them, and the solution in the AWS cookbook and/or the gem_metadata solution both work well for that.  But neither of them vendor the gem.

I think the problem of a completely airgapped environment runs afoul of the 95% rule:

```
Support the 95% use case

Unfortunately new functionality comes with a maintenance cost and because of this we must be mindful of all new functionality we introduce. Chef-managed community cookbooks aim to support the use cases of 95% of users. Sometimes edge cases introduce extreme code complexity and maintenance burden. In this case we'll defer the change to a wrapper cookbook or purpose-built fork.
```

https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/COOKBOOK_TEAM.MD#support-the-95-use-case

The support burden is high and its likely something that we don't want to support in community cookbooks.

The better solution is likely to be writing a custom cookbook that runs very early in the run_list and vendors all the gems that the node needs, then later cookbooks should be all idempotent and be fine (if chef_gem or gem_package itself tries to hit rubygems.org when the gem is already installed, that's a use case we do care about, and AFAIK we've fixed those bugs awhile back).

**Comment by lamont-granquist** [comment]
noah points out that we support normal airgapped envs just fine via rubygems_url pointing at a mirror -- but this is a "mirrorless airgapped++" environment which i think is just a use case that we never intended to support but only accidentally supported with vendored gems.  definitely not the 95% case.

**Comment by lamont-granquist** [comment]
and @someara there's nothing particularly magical about the AWS approach.

its just the usual thing of:

1.  all `requires` lines must be lazied into providers/actions
2.  chef_gem installation must happen before the requires line is evaluated

it just wraps that into a library where you do:

1.  require the gem, and carry on if it loads
2.  rescue LoadError, then chef_gem install it, then require it again

then you call that library function from every provider.

you could also write a recipe that did a chef_gem and `include_recipe` in every provider before requiring the gem, but i think you'll wind up needing to fall back to `compile_time true` in the chef_gem resource.   it feels to me like the require-rescue-LoadError approach will be lighterweight idempotency even though its ruby-idempotency and not chef-idempotency.  since you may beat the crap out of the code with dozens or hundreds of calls to aws-related resources in some cases, it feels bad to create dozens or hundreds of chef_gem resources even if they're idempotent.  the require line will be a lot faster.  could also use `unless defined?(Whatever)` or any other ruby approach as well for idempotency.

and its a bit better than the old approach of requiring that the user always know that they need to manually include some default recipe before they use any of the resources, which is fussy.

in the generic case where the resources commonly need much more than just a chef_gem installed then the include_recipe approach may be better / more flexible, otherwise you're just writing a recipe that lives in library code which is going to get a bit fugly.

but none of that solves the "i don't even have a rubygem mirror" problem.  a custom cookbook that vendors the gem(s) in that case seems the only approach.

**Comment by swimfrog** [comment]
Thanks @someara and @lamont-granquist for the detailed explanation. I've decided not to use the cookbook in my environment, since the only LWRP I was really using is `docker_service`, so the gem wasn't buying me anything anyway, just preventing the parts I needed from running. Asserting the bits that `docker_service` provides isn't difficult.

I can definitely envision running into this in the future, and the approach of vendoring gems in a wrapper cookbook that runs before anything else makes sense to me. I had briefly tried to just wrap the cookbook and vendor the gems from the wrapper, but I found that the dependent cookbook ran first, so I wasn't able to vendor the gem in that way. Running it from a completely isolated cookbook hadn't occurred to me, so I'll keep that in my back pocket in case I ever need to do it.

Just a note that the PR I submitted did solve the issue in the airgapped environment, but it's a little hacky. It may be worth considering whether or not ChefGem could be updated to accept an array of local gems, since the typical rubygems dependency resolution doesn't seem to work with --local mode, so if the gem you want to install has *any dependencies at all*, and you want to install it in --local mode, it will not work. I guess this is somewhat similar to [this issue](https://github.com/chef/chef/issues/3456)

**Comment by someara** [comment]
The major motivation for vendoring the gem is because one of its dependencies requires a compiling a native extension.

Installing it via chef_gem would require build_essential, which causes an arms race where half the machine configuration is happening in the compilation phase (pointing at internal repos, installing compilers, etc).

All that just to install a few kilobytes of json parsing bits.

The real answer here would be for Chef to ship these bits in the omnibus client.

My hands are tied.

-s

**Comment by lamont-granquist** [comment]
if you expose resources and only require/install the gem in provider code then you don't have to run build-essentials at compile time.

**Comment by lamont-granquist** [comment]
looks like the aws cookbook is using v2 of the aws gem which is not a native gem so it just installs it via the gem metadata

**Comment by lamont-granquist** [comment]
This was the old pattern:

https://github.com/chef-cookbooks/aws/blob/f422cdefad537a9b325c2339562ab7a451d0a3a9/libraries/aws.rb

The way that was used had a few layers of indirection but it boiled down to no more than:

```ruby
action :whatever do
  require_aws_sdk
end

action_class do
  include Opscode::Aws
end
```

include the library in all your providers / action classes, and then invoke the require_gem_name function in all actions.

**Comment by bcg62** [comment]
Also in this situation and looking for a way to vendor the gem myself in a wrapper cookbook

**Comment by iennae** [comment]
@lamont-granquist has provided an extensive response to this. If this is still a problem for you and the explanation is not sufficient, please re-open with additional details.
