### ISSUE TITLE
Add support for a docker_plugin resource

### ISSUE THREAD

**Issue by elijah** [chef-cookbooks/docker#942]
### Cookbook version
latest

### Chef-client version
irrelevant

### Platform Details
irrelevant

### Scenario:

I want to be able to config-manage installation docker plugins - my eventual intent is to be able to use the netshare volume driver in order to mount nfs shares as docker volumes.

### Steps to Reproduce:
Missing functionality.

### Expected Result:
Sucessfully install a docker volume driver, and then install an NFS volume.

### Actual Result:
Unsupported feature.

**Comment by horazont** [comment]
We’re interested in implementing this. The docker-api gem does not seem to implement a wrapper for the respective API(*). We would thus be implementing this in terms of ``Docker.connection.{get,post,delete}``, if that is okay.

We’re thinking of a ``docker_plugin`` resource which allows to:

* ``:install`` a plugin with an alias, configuration options and (a) either an explicit list of permissions or (b) a blanket-statement to allow any permissions requested by the plugin.
* ``:update`` the configuration options and leave the plugin unchanged otherwise
* ``:enable`` the plugin
* ``:disable`` the plugin
* ``:remove`` the plugin

Is this in line with the goals of this cookbook?

---
*: Personally, it seems to me as if the [docker-api folks are currently not interested in adding functionality](https://github.com/swipely/docker-api/pull/462#issuecomment-269234839) ([confirmed again in 2017](https://github.com/swipely/docker-api/pull/504#issuecomment-347134993)) which depends on a specific modern version of the docker API for compatibility reasons. However, if you folks would strongly prefer the use of a wrapper in docker-api, we can go over there and try to figure out a solution.
