### ISSUE TITLE
No recipes?

### ISSUE THREAD

**Issue by CodingSpiderFox** [chef-cookbooks/docker#964]
Why doesn't this cookbook have recipes, only libraries?

I want to create a role which installs docker with corporate proxy settings and other options on all my linux nodes. 

I want to be able to do that by simply drag&drop the recipe into the role in my chef web UI and specifying the attributes for the role.

If you find this is a dumb question, please tell me why. I'm still quite new to chef and sometimes it is not that self explaining

**Comment by chasebolt** [comment]
This cookbook is meant to be used in a wrapper cookbook. Where you would setup the resources. Because docker service is highly configurable, depending on using swarm, volume drivers, etc - having a default recipe isn’t worth it. You can create a small wrapper cookbook that then sets up docker as you desire using examples from the readme.

**Comment by CodingSpiderFox** [comment]
Thanks
